#!/bin/sh
export APPLICATION_AIRPORT_DAYSUNTILSTALE=0
export APPLICATION_AIRPORT_API_APIKEY=key
export APPLICATION_AIRPORT_API_BASEURL=http://localhost
export APPLICATION_RESTAURANT_DAYSUNTILSTALE=0
export APPLICATION_RESTAURANT_API_APIKEY=key
export APPLICATION_RESTAURANT_API_BASEURL=http://localhost
export APPLICATION_REDIS_HOST=localhost
export APPLICATION_REDIS_PORT=6379
export SERVER_PORT=8080
export LOGGING_LEVEL_ROOT=INFO
docker-compose up -d
