spring:
  graphql:
    graphiql:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: "localhost"
      port: 6370
application:
  airport:
    daysUntilStale: 0
    api:
      apiKey: "k"
      baseUrl: "https://airports-by-api-ninjas.p.rapidapi.com/v1/airports"
  restaurant:
    daysUntilStale: 0
    api:
      apiKey: "k"
      baseUrl: "https://maps.googleapis.com/maps/api/place"
  redis:
    hostname: "http://0.0.0.0"
    port: 6379
    username: "redis-user"
    password: "redis-password"
  security:
    securityHeaderKey: "key"
    securityHeaderValue: "value"
logging:
  level:
    web: "debug"
    com:
      skylunch: "debug"
