spring:
  redis:
    host: "localhost"
    port: 6370
  main:
    allow-bean-definition-overriding: true
application:
  airport:
    daysUntilStale: 0
    api:
      apiKey: "k"
      baseUrl: "http://localhost"
  restaurant:
    daysUntilStale: 0
    api:
      apiKey: "k"
      baseUrl: "http://localhost"
  redis:
    host: "localhost"
    port: 6370
