#digitalocean-simple-k3s-setup
write_files:
- path: /etc/nixos/host.nix
  permissions: '0644'
  content: |
    {pkgs, ...}:
    {
      networking.firewall.allowedTCPPorts = [ 6443 ];
      environment.systemPackages = with pkgs; [ neovim k3s git ];
      services = {
        k3s = {
          enable = true;
          disableAgent = true;
          role = "server";
        };
      };
      programs = {
        neovim = {
          enable = true;
          defaultEditor = true;
          vimAlias = true;
        };
        zsh = {
          enable = true;
          enableCompletion = true;
          autosuggestions.enable = true;
          syntaxHighlighting.enable = true;
        };
      };
      users.defaultUserShell = pkgs.zsh;
    }
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | PROVIDER=digitalocean NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-22.05 bash 2>&1 | tee /tmp/infect.log
