apiVersion: apps/v1
kind: Deployment
metadata:
  name: skylunch-deployment
  labels:
    app: skylunch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skylunch
  template:
    metadata:
      labels:
        app: skylunch
    spec:
      containers:
      - name: skylunch
        image: siph/skylunch:latest
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATION_AIRPORT_API_APIKEY
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: rapid-api-key
        - name: APPLICATION_RESTAURANT_API_APIKEY
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: google-api-key
        - name: SPRING_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: redis-host
        - name: SPRING_REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: redis-port
        - name: SPRING_REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: redis-username
        - name: SPRING_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skylunch-secret
              key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: skylunch-service
spec:
  type: LoadBalancer
  selector:
    app: skylunch
  ports:
    - port: 8080
      targetPort: 8080
