apiVersion: apps/v1
kind: Deployment
metadata:
  name: skylunch-deployment
  namespace: skylunch
  labels:
    app: skylunch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skylunch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skylunch
    spec:
      containers:
        - name: skylunch
          image: siph/skylunch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: APPLICATION_AIRPORT_API_APIKEY
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: rapid-api-key
            - name: APPLICATION_RESTAURANT_API_APIKEY
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: google-api-key
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: redis-host
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: redis-port
            - name: SPRING_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: redis-username
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skylunch-secret
                  key: redis-password
