#cloud-config
write_files:
  - path: /etc/nixos/host.nix
    permissions: '0644'
    content: |
      {pkgs, ...}:
      {
        networking.firewall.allowedTCPPorts = [ 80 443 6443 10250 ];
        environment.systemPackages = with pkgs; [ k3s ];
        services = {
          k3s = {
            enable = true;
            disableAgent = false;
            role = "server";
          };
        };
        programs = {
          neovim = {
            enable = true;
            defaultEditor = true;
            vimAlias = true;
          };
        };
        system.stateVersion = "22.11";
      }
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | PROVIDER=digitalocean NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-22.11 bash 2>&1 | tee /tmp/infect.log
