name: "Test Coverage Badge"
on:
  workflow_call:
jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout badges
      uses: actions/checkout@v3
      with:
        ref: badges
        path: badges
    - name: Retrieve jacoco artifact
      uses: actions/download-artifact@v3
      with:
        name: jacoco-csv
        path: target/site/jacoco
    - name: Generate Badges
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"
    - name: Commit and push
      run: |
        cd badges
        if [[ `git status --porcelain *.svg` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.svg
          git commit -m "Autogenerated JaCoCo coverage badge" *.svg
          git push
        fi
