name: "Tests"
on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, edited ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: maven build
      run: nix develop --command mvn install -DskipTests=true
    - name: ktlint
      run: nix develop --command mvn ktlint:check
    - name: restaurant tests
      run: nix develop --command mvn test -Dtest=RestaurantServiceTests
    - name: airport tests
      run: nix develop --command mvn test -Dtest=AirportServiceTests
