name: "Tests"
on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, edited ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # Lint
    - name: ktlint
      run: nix develop .#build --command mvn ktlint:check
      # Build
    - name: maven build
      run: nix develop .#build --command mvn install -DskipTests=true
      # Unit Tests
    - name: header filter tests
      run: nix develop .#build --command mvn test -Dtest=HeaderBasedWebFilterTests
    - name: property validation tests
      run: |
        nix develop .#build --command mvn test -Dtest=AirportApiPropertiesTests
        nix develop .#build --command mvn test -Dtest=AirportPropertiesTests
        nix develop .#build --command mvn test -Dtest=RedisApplicationPropertiesTests
        nix develop .#build --command mvn test -Dtest=RestaurantApiPropertiesTests
        nix develop .#build --command mvn test -Dtest=RestaurantPropertiesTests
        nix develop .#build --command mvn test -Dtest=SecurityPropertiesTests
    - name: type conversion tests
      run: nix develop .#build --command mvn test -Dtest=SearchDTOTests
      # Integration Tests
    - name: restaurant tests
      run: nix develop .#build --command mvn test -Dtest=RestaurantServiceTests
    - name: airport tests
      run: nix develop .#build --command mvn test -Dtest=AirportServiceTests
      # Test Coverage
    - name: jacoco report
      run: nix develop .#build --command mvn jacoco:report
    - name: post coverage percentage
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 60
        min-coverage-changed-files: 60
    - name: store reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/
