name: "Tests"
on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, edited ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # Lint
    - name: ktlint
      run: nix develop --command mvn ktlint:check
      # Build
    - name: maven build
      run: nix develop --command mvn install -DskipTests=true
      # Unit Tests
    - name: header filter tests
      run: nix develop --command mvn test -Dtest=HeaderBasedWebFilterTests
      # Integration Tests
    - name: restaurant tests
      run: nix develop --command mvn test -Dtest=RestaurantServiceTests
    - name: airport tests
      run: nix develop --command mvn test -Dtest=AirportServiceTests
